export const products = [
  {
    id: 1,
    title: "Producto 1",
    price: 25000,
    description: "El producto es el 1",
    category: "Uno",
    img: "https://res.cloudinary.com/dyt4eknl1/image/upload/v1677352509/cld-sample-5.jpg",
  },
  {
    id: 2,
    title: "Producto 2",
    price: 2000,
    description: "El producto es el 2",
    category: "Dos",
    img: "https://res.cloudinary.com/dyt4eknl1/image/upload/v1677352508/cld-sample-3.jpg",
  },
  {
    id: 3,
    title: "Producto 3",
    price: 56000,
    description: "El producto es el 3",
    category: "Tres",
    img: "https://res.cloudinary.com/dyt4eknl1/image/upload/v1677352507/cld-sample.jpg",
  },
  {
    id: 4,
    title: "Producto 4",
    price: 67000,
    description: "El producto es el 4",
    category: "Cuatro",
    img: "https://res.cloudinary.com/dyt4eknl1/image/upload/v1677352509/cld-sample-4.jpg",
  },
  {
    id: 5,
    title: "Producto 5",
    price: 89000,
    description: "El producto es el 5",
    category: "Cinco",
    img: "https://res.cloudinary.com/dyt4eknl1/image/upload/v1677352508/cld-sample-3.jpg",
  },
  {
    id: 6,
    title: "Producto 6",
    price: 85000,
    description: "El producto es el 6",
    category: "seis",
    img: "https://res.cloudinary.com/dyt4eknl1/image/upload/v1677352509/cld-sample-5.jpg",
  },
  {
    id: 7,
    title: "Producto 7",
    price: 67000,
    description: "El producto es el 7",
    category: "Siete",
    img: "https://res.cloudinary.com/dyt4eknl1/image/upload/v1677352509/cld-sample-4.jpg",
  },
];
